### ISSUE TITLE
Can't Run the Program

### ISSUE THREAD

**Issue by mightbeh** [stephsamson/weather-bot#3]
I tried to run the code and understand it but I believe there is some problem in the virtual env. I'm not sure.

Just check the screenshots:

![annotation](https://user-images.githubusercontent.com/38653422/47980571-4f2d3080-e0ee-11e8-8643-8c8f23635f8c.png)

**Comment by kasteph** [comment]
Hi @Dharani-0111 this error means that you're missing an email address associated with the Zulip bot. You can find this when you log in to your Zulip account, then go to `Settings > Your bots`.
